# Generated by Django 3.0.8 on 2020-07-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixpol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
