# Generated by Django 3.0.8 on 2020-08-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixpol', '0004_auto_20200803_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='shortname',
            field=models.CharField(default='tucson', max_length=20),
            preserve_default=False,
        ),
    ]
