# Generated by Django 3.0.8 on 2020-08-03 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixpol', '0005_location_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child', to='fixpol.Location'),
        ),
    ]
