# Generated by Django 3.0.8 on 2020-08-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixpol', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
