# Generated by Django 3.0.8 on 2020-08-05 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixpol', '0010_searchcriteria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchCriteria',
            new_name='Criteria',
        ),
    ]
