# Generated by Django 3.0.8 on 2020-08-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixpol', '0011_auto_20200805_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criteria',
            options={'verbose_name_plural': 'criteria'},
        ),
        migrations.AddField(
            model_name='criteria',
            name='text',
            field=models.CharField(default='world.usa.arizona.tucson-Environment', max_length=200),
            preserve_default=False,
        ),
    ]
