# Generated by Django 3.0.8 on 2020-08-05 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixpol', '0012_auto_20200805_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='fixpol.Location'),
        ),
    ]
