# Generated by Django 3.0.8 on 2020-08-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixpol', '0013_auto_20200805_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impact',
            name='text',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='hierarchy',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
