# Generated by Django 3.0.8 on 2020-08-07 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixpol', '0014_auto_20200806_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=1000)),
                ('impacts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laws', to='fixpol.Impact')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laws', to='fixpol.Location')),
            ],
            options={
                'verbose_name_plural': 'laws',
            },
        ),
    ]
