# Generated by Django 3.0.8 on 2020-08-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixpol', '0018_law_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='key',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
