# Generated by Django 3.0.8 on 2020-08-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixpol', '0021_auto_20200809_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['hierarchy']},
        ),
        migrations.AlterField(
            model_name='criteria',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
