# Generated by Django 3.0.8 on 2020-08-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixpol', '0022_auto_20200813_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='hierarchy',
            field=models.CharField(max_length=200),
        ),
    ]
