# Generated by Django 3.0.8 on 2020-10-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='bill_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='law',
            name='doc_date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='law',
            name='relevance',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
