# Generated by Django 3.0.8 on 2020-10-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0003_location_legiscan_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impact',
            options={'ordering': ['date_added']},
        ),
        migrations.AlterModelOptions(
            name='law',
            options={'ordering': ['key'], 'verbose_name_plural': 'laws'},
        ),
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('fob_method', models.CharField(max_length=6)),
                ('generated_date', models.DateField()),
                ('hashcode', models.CharField(max_length=32)),
                ('size', models.PositiveIntegerField()),
                ('desc', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'hashcodes',
                'ordering': ['item_name'],
                'unique_together': {('item_name', 'fob_method')},
            },
        ),
    ]
