# Generated by Django 3.0.8 on 2020-10-31 13:07

import cfc_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0007_auto_20201031_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='key',
            field=models.CharField(default=cfc_app.models.get_default_law_key, max_length=25, unique=True),
        ),
    ]
