# Generated by Django 3.0.8 on 2020-11-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0008_auto_20201031_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='summary',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='law',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
