# Generated by Django 3.0.8 on 2020-11-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0009_auto_20201107_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='relevance',
            field=models.TextField(max_length=800, null=True),
        ),
    ]
