# Generated by Django 3.0.8 on 2021-03-03 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0010_auto_20201107_1454'),
    ]

    operations = [
    migrations.RenameField('location', 'desc', 'longname'),
    ]
