# Generated by Django 3.0.8 on 2021-03-03 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0012_auto_20210303_0218'),
    ]

    operations = [
    migrations.RenameField('Impact', 'text', 'iname'),
    ]
