# Generated by Django 3.0.8 on 2021-03-03 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfc_app', '0013_auto_20210303_0236'),
    ]

    operations = [
    migrations.RenameField('Criteria', 'text', 'crtext'),
    ]
