#!/usr/bin/env bash
# By Tony Pearson, IBM, 2020
#
# This script runs the application with PostgreSQL (see STAGE2.md for details)
# Designed for use with operating system "cron" for background tasks
#
# Examples:
#
# cron2 get_api_data    Invokes Legiscan.API and creates AZ.json, OH.json
# cron2 scan_json       Scans AZ.json and OH.json, converts PDF/HTML -> TXT
# cron2 analyze_text    Analyzes TXT files, assigns IMPACT, loads database
#
parms="$@"
export USE_SQLITE3='False'
cd /home/tpearson/Develop/legit-info && pipenv run python manage.py $parms
