#!/usr/bin/env bash
# This script runs the application with Postgresql (see STAGE2.md for details)
#
# Examples:
# ./stage2 runserver localhost:3000   <-- default if nothing specified
# ./stage2 shell
# ./stage2 makemigrations
# ./stage2 migrate
# ./stage2 dbshell
# ./stage1 qcluster
parms="$@"
if [ "$#" -eq 0 ]; 
    then cmd="gunicorn -b 0.0.0.0:3000 --env DJANGO_SETTINGS_MODULE=cfc_project.settings cfc_project.wsgi"
else
    cmd="python3 manage.py $parms"
fi
echo $cmd
USE_SQLITE3='False' $cmd
