#!/usr/bin/env bash
# This script runs the application with SQLite3 (see STAGE1.md for details)
#
# Examples:
# ./stage1 runserver localhost:3000   <--- default if nothing specified
# ./stage1 shell
# ./stage1 makemigrations
# ./stage1 migrate
# ./stage1 dbshell
parms="$@"
if [ "$#" -eq 0 ]; 
    then parms="runserver localhost:3000"
fi
USE_SQLITE3='True' python3 manage.py $parms
