#!/usr/bin/env bash
# This script runs the application with Postgresql (see STAGE2.md for details)
#
# Examples:
# ./stage2 runserver localhost:3000   <-- default if nothing specified
# ./stage2 shell
# ./stage2 makemigrations
# ./stage2 migrate
# ./stage2 dbshell
# ./stage1 qcluster
parms="$@"
if [ "$#" -eq 0 ]; 
    then parms="runserver localhost:3000"
fi
USE_SQLITE3='False' python manage.py $parms
