# Generated by Django 3.0.8 on 2020-08-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
