# Generated by Django 3.0.8 on 2020-08-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_delete_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
