apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: legitinfo-db
  name: legitinfo-db
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: registry.redhat.io/rhscl/postgresql-13-rhel7:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
